name: Deploy Firestore Rules

on:
  push:
    branches: [master]
    paths:
      - "firestore.rules"
  workflow_dispatch:

jobs:
  deploy-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w9jds/firebase-action@v13.29.1
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
